### ISSUE TITLE
Have you compared this with state-of-the-art U-Net?

### ISSUE THREAD

**Issue by WrathofBhuvan11** [lelechen63/MRI-tumor-segmentation-Brats#5]

**Comment by parvezamu** [comment]
You can compare because in Unet all the modalities are passed through a single path but different modalities may have different information so two-way path network is good...........also you can try unet proposed by Dolz...........and latest try this MDU-Net: Multi-scale Densely Connected U-Net for
biomedical image segmentation..the main thing is about the feature learning..............
